apply:
	feast apply

teardown:
	feast teardown

ui:
	feast ui

preprocess_data:
	cd preprocessing && python preprocess_data.py

enable_alpha:
	feast alpha enable on_demand_transforms

materialize:
	feast  materialize  1997-07-16T19:20:01 2024-07-16T19:20:01